In [1]:
import pandas as pd

In [ ]:
names = ['sumlev', 'region', 'division', 'state', 'name', 'census2010pop', 'estimatesbase2010', 'popestimate2010', 'popestimate2011', 'popestimate2012', 'popestimate2013', 'popestimate2014', 'popestimate2015', 'popestimate2016', 'popestimate2017', 'popestimate2018', 'popestimate2019', 'popestimate042020', 'popestimate2020']
state_pops = pd.read_csv("data/nst-est2020.csv", names=names, header=0)
state_pops

In [ ]:
netflix = pd.read_csv("data/netflix_titles.csv", sep="|", index_col=0)

In [6]:
tit = pd.read_csv('D:\\karan data\\Data for Preprocessing\\titanic.csv', na_values='?')

In [7]:
tit

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [ ]:
dataframe = df 
index = name

	                        mpg	cylinders	displacement	horsepower	weight	acceleration	model_year	origin
name								
chevrolet chevelle malibu	18.0	8	307.0	130.0	3504	12.0	70	usa
buick skylark               320	15.0	8	350.0	165.0	3693	11.5	70	usa
plymouth satellite	        18.0	8	318.0	150.0	3436	11.0	70	usa
amc rebel sst	            16.0	8	304.0	150.0	3433	12.0	70	usa
ford torino	                17.0	8	302.0	140.0	3449	10.5	70	usa
...	...	...	...	...	...	...	...	...
ford mustang gl	            27.0	4	140.0	86.0	2790	15.6	82	usa
vw pickup	                44.0	4	97.0	52.0	2130	24.6	82	europe
dodge rampage	            32.0	4	135.0	84.0	2295	11.6	82	usa


df.index.is_unique  # check duplicate value in the index
df.index.value_counts()
df.index.name = 'car_model'


df['weight'].idxmax()

df dataframe  k ander weight column uske ander maximum value aur uska index

In [ ]:
tit["fare"].apply(lambda x: f"${x*24}") 
0                   $5072.1
1       $3637.2000000000003
2       $3637.2000000000003
3       $3637.2000000000003
4       $3637.2000000000003
               ...

In [ ]:
 5 seconds
1        3-5 seconds
2                NaN
3         10 seconds
4          2 minutes
            ...     
88120      3 minutes
88121     20 seconds
88122     20 seconds
88123      2 minutes
88124      3 minutes
Name: duration, Length: 88125, dtype: object

ufos["duration"].str.replace("seconds|minutes", "", regex=True)

0          5 
1        3-5 
2         NaN
3         10 
4          2 
         ... 
88120      3 
88121     20 
88122     20 
88123      2 
88124      3 
Name: duration, Length: 88125, dtype: object

In [ ]:
duration
0	45 seconds
1	2 hours
2	30 minutes
3	10 minutes
4	5 seconds
5	Nan

def abbrv(reo):
    return reo.group()[0]


ufos["duration"].str.replace("seconds|minutes|hours", abbrv, regex=True)

0    45 s
1     2 h
2    30 m
3    10 m
4     5 s
5     Nan



ufos[ufos["duration"].str.contains("day|week|month", na=False)]

In [ ]:
titanic.loc[5:10:2] # need row from 5 to 10 having 2 increment

In [ ]:
titanic[titanic.pclass != 1]  # and &, or | (for dax && and ||)

newly_built = houses["yr_built"] >= 2014
newly_renovated = houses["yr_renovated"] >= 2014
recent_homes = newly_built | newly_renovated
houses[recent_homes]
houses[~recent_homes]

netflix[netflix.director.notna()]

In [ ]:
tit.drop(tit.index[:10])  # drop 1st 10 rows

In [ ]:
tit.loc[[2], ['name']] = 'karan' # update 2 row and name column element to karan
tit.loc[[2], ['sex']] = 'male'   # update 2 row and sex column element to male

countries.loc[["Finland", "Denmark", "Iceland", "Sweden", "Norway"], ['Regional indicator', 'isCold']] = ["Nordic Countries", "yes!" ]

In [ ]:
names = ['sumlev', 'region', 'division', 'state', 'name', 'census2010pop', 'estimatesbase2010', 'popestimate2010', 'popestimate2011', 'popestimate2012', 'popestimate2013', 'popestimate2014', 'popestimate2015', 'popestimate2016', 'popestimate2017', 'popestimate2018', 'popestimate2019', 'popestimate042020', 'popestimate2020']
state_pops = pd.read_csv("data/nst-est2020.csv", names=names, header=0)
state_pops

In [ ]:
house.describe(include = 'O')

In [1]:
df_tit.insert(2, 'female', 'Jnani')

#df_tit dataframe m 2nd position pr column name 'female' h hiske ander value h 'Jnani'

NameError: name 'df_tit' is not defined

In [ ]:
df.fillna({'name': 'lale', 'age': '23'})
df['age'].fillna(23, inplace = True)

In [ ]:
df.fillna({'name':'lale', 'age': '23'}, inplace=True)
df['age'].fillna(23, inplace=True)
df['name'].fillna('lale', inplace=True)

In [ ]:
dt[dt['time']  <= dt.time(14,22,00)]

In [ ]:
	First Name	Gender	Start Date	Last Login Time	Salary	Bonus %	Senior Management	Team
0	Douglas	Male	08-06-1993	12:42 PM	97308	6.945	True	Marketing
1	Thomas	Male	3/31/1996	6:53 AM	61933	4.170	True	NaN
2	Maria	Female	4/23/1993	11:17 AM	130590	11.858	False	Finance
3	Jerry	Male	03-04-2005	1:00 PM	138705	9.340	True	Finance
4	Larry	Male	1/24/1998	4:47 PM	101004	1.389	True	Client Services

In [ ]:
emp['Start Date'] = pd.to_datetime(emp['Start Date'], format='mixed', errors='coerce')

In [ ]:
# 12:42 PM ---> 12:42:00
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time

In [ ]:
emp['login_time'] < dt.time(6,34,45)

In [ ]:
employees[employees["Last Login Time"] < dt.time(12, 0, 0)]

In [ ]:
df['start_date'].between("1991-01-01", "1992-01-01")

dt.time(8,30)

In [ ]:
employees[employees["Start Date"].between("1991-01-01", "1992-01-01")]

employees[employees["Last Login Time"].between(dt.time(8, 30), dt.time(12, 0))]

In [ ]:
emp[emp['login_time'].between(dt.time(8,0,0), dt.time(2,0,0))]

In [10]:
tit.set_index(['sex', 'age'], inplace=True)

In [ ]:
tit['cabin'].str[0]

In [ ]:
		    population
state	year	
AK	    1990	553290.0
        1991	570193.0
AL	    1990	4050055.0
        1991	4099156.0

# state.index.get_level_values(0) 

Index(['AK', 'AK', 'AK', 'AK', 'AK', 'AK', 'AK', 'AK', 'AK', 'AK',
       ...
       'WY', 'WY', 'WY', 'WY', 'WY', 'WY', 'WY', 'WY', 'WY', 'WY'],
      dtype='object', name='state', length=1272)

# state.index.get_level_values(1) 

Index([1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999,
       ...
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013],
      dtype='int64', name='year', length=1272)

In [ ]:
df_multiindex.sort_index().loc[[("female", 3), ("male", 1)]]
df.sort_index().loc[[(),()]]

pops.loc[["CA", "AK"]]

pops.loc[['AK','AL'], [1990,1991], :]

In [ ]:
		       fare
sex	   pclass	
female	1	109.412385
        2	23.234827
        3	15.324250
male	1	69.888385
        2	19.904946
        3	12.415462

In [ ]:
df.loc[(['02-01-2014', '04-01-2104']), ['high', 'low']]

In [ ]:
tech.loc[(['02-01-2014', '03-01-2014']), ['high', 'low']]

In [ ]:
df.loc[(slice('02-03-2014', '15-03-2014'), ['', '']), ['', '']]

In [ ]:
df.loc[(slice('02-01-2014', '05-01-2014'), ['googl', 'msft']), :]

In [ ]:
df.loc[(slice('02-01-2014', '12-01-2024'), ['GOOGL', 'MSFT']), 'close':'low']

In [ ]:
tech.sort_index().loc[(slice('02-01-2014' , '05-01-2014'), ['GOOGL', 'MSFT']), 'close': 'low']

In [ ]:
tech.loc[(['02-01-2014', '03-01-2014'], ['GOOGL', 'MSFT']), ['high', 'low'] ]

In [ ]:
			month	year	day	open	close	high	low	volume
date	name	volume_type								
01-02-2016	GOOGL	high	2	2016	1	771.26	770.77	777.59	761.38	5576089
01-02-2017	AAPL	high	2	2017	1	127.03	128.75	130.49	127.01	111985040
01-02-2018	AMZN	high	2	2018	1	1445.00	1390.00	1459.88	1385.14	9113808
01-02-2019	AMZN	high

In [ ]:
tech.sort_index().loc[(slice('01-01-2019', '31-01-2019'), slice(None), 'high'), :]

In [ ]:
df_multiindex.sort_index(level=0)

		        fare
sex	    pclass	
female	1	109.412385
        2	23.234827
        3	15.324250
male	1	69.888385
        2	19.904946
        3	12.415462

In [ ]:
df_multiindex.sort_index(level=1)

		        fare
sex	    pclass	
female	1	109.412385
male	1	69.888385
female	2	23.234827
male	2	19.904946
female	3	15.324250
male	3	12.415462

df_multiindex.sort_index(level=[1,0],ascending=[False,True])

In [ ]:
tech.reset_index(['volume_type', 'name'], drop = False)
tech.droplevel(['volume_type', 'name'])

In [ ]:
df.index.reorder_level([2,1,0])

In [ ]:
tech.index.reorder_levels([2,1,0])

In [ ]:
tidx = tech.index
tidx.set_names(['Trading Date', 'Volume Category', 'Ticker'], inplace = True)

In [ ]:
tidx.sortlevel((0,1,2), ascending = [True, True, False])

In [ ]:
# Working with different dataframe

In [ ]:
DataFrame.merge(right, how='inner', on=None, left_on=None, right_on=None, 
                left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=None, 
                indicator=False, validate=None)

In [ ]:
week_1.merge(week_2, how="outer", on="Customer ID", suffixes=[" - Week 1", " - Week 2"])

In [ ]:
merged = week_1.merge(week_2, how="outer", on="Customer ID", suffixes=[" - Week 1", " - Week 2"], indicator=True) ---indicator

In [ ]:
week_1.merge(food, how="left", on="Food ID", sort = True) ---sort parameter

In [ ]:
week_1.merge(customer,how = 'left', left_on= 'Customer ID', right_on= 'ID').head(3)

In [ ]:
combine = midterms.merge(finals, how = 'inner', on = ['first', 'last'], suffixes= ['_midterm', '_final'])

In [12]:
tit['fare'] = tit['fare'].astype('float')

In [14]:
tit.head(2)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"

In [19]:
tit.loc[tit['sex'] == 'male', 'fare'] += 10

In [ ]:
combine.loc[combine['extra_credit'] == True, 'Avg'] +=10

In [ ]:
#csv files 
transactions = pd.concat(
    (pd.read_csv("transactions_2014.csv"), 
     pd.read_csv("transactions_2015.csv")),
).drop(["Unnamed: 0"], axis=1)

In [ ]:
# Excel 

# Read in two Excel sheets and concatenate them into a single DataFrame

transactions = pd.concat(
    pd.read_excel("DataForChandler.xlsx", sheet_name=[1, 2]),  #  specify sheets 1 and 2 to grab correct years
    ignore_index=True  #  specify to create consecutive index across sheets
).drop(["Unnamed: 0"], axis=1)  #  drop index col

In [ ]:
pd.concat(objs, *, axis=0, join='outer', ignore_index=False, keys=None, levels=None,
             names=None, verify_integrity=False, sort=False, copy=None)

In [ ]:
# use key parameter
pd.concat([Ivies_Dataset, Eng_Dataset], keys=['Ivi', 'Eng'], names=['dataset'])

In [ ]:
pd.concat([Mod_Ivies, Mod_Eng], verify_integrity=True)

In [ ]:
pd.concat([Eng_Demo, Ivies_Dataset], join= 'inner', ignore_index=True)

In [ ]:
pd.concat([Eng_Demo, Ivies_Dataset], join= 'inner')

In [ ]:
merged_Data['Category'] = merged_Data.apply(lambda x : 'yes' if x['School Name'] == x['school_name'] else 'no', axis=1)

In [ ]:
merged_Data['Comparsion'] = np.where(merged_Data['School Name'] == merged_Data['school_name'], 'yes', 'no')

In [ ]:
np.where(df['name'] == df['coll_name'], 'yes', 'no')

In [ ]:
df['date'].dt.strftime('%Y-%b-%d')

In [ ]:
pd.to_timedelta(data["Duration"]).dt.components.hours
pd.to_timedelta(data["Duration"]).dt.components.minutes

In [ ]:
retail['date'].dt.strftime('%Y-%b-%d').head()

In [ ]:
pd.Timestamp("4th of july 1776")
pd.Timestamp("2025-01-01")
pd.Timestamp(2027, 3, 12, 18, 23, 49)

In [ ]:
df_4['Date'] = pd.to_datetime(df_4['Date'], format='%d-%b-%y') 

# lets say Date is like (2010,2011,2012,2013,2014,2015)
df_4['Date'] = pd.to_datetime(df_4['Date'], format='%Y')

In [ ]:
pd.date_range(start = '10 may 2020', end = '')
pd.date_range(start = '', period = 10, freq = '10d')

In [ ]:
pd.date_range(start = '10 may 2020', end = '20 june 2020')

In [ ]:
pd.date_range(start = '10 may 2020', end = '20 june 2020')

In [ ]:
pd.date_range(start = '1/20/2020', periods = 10)

In [ ]:
pd.date_range(start = "23 september 2024", periods = 10, freq = 'y')

pd.date_range(start = '', end = '', freq = pd.DateOffset(years=1))

In [ ]:
pd.date_range(start = '08/31/2023', periods = 10, freq = 'W')
birthdays = pd.date_range(start="1991-04-12", end="2023-04-12", freq=pd.DateOffset(years=1))

In [ ]:
pd.DateOffset(days=3, hours=4)

In [ ]:
brent_4.set_index (brent_4.index + pd.DateOffset(hours = 3))
df_3.set_index(df_2.index + pd.DateOffset(days = 1, hours = 2))

In [ ]:
transactions['transactions_diff_days'] = transactions['date'].max() - transactions['date'] 
transactions['transactions_diff_days'] + 21 # causing an error
transactions['transactions_diff_days_21'] = transactions['transactions_diff_days'] + pd.to_timedelta(21, unit = 'D')

	date	store_nbr	transactions	transactions_diff_days	transactions_diff_days_21
0	2013-01-01	25	770	1687 days	1708 days
1	2013-01-02	1	2111	1686 days	1707 days
2	2013-01-02	2	2358	1686 days	1707 days
3	2013-01-02	3	3487	1686 days	1707 days
4	2013-01-02	4	1922	1686 days	1707 days
...	...	...	...	...	...
83483	2017-08-15	50	2804	0 days	21 days
83484	2017-08-15	51	1573	0 days	21 days
83485	2017-08-15	52	2255	0 days	21 days

In [ ]:
# similar to group by on monthly level and gives value on median value 
brent_new.resample('M').median()

In [ ]:
Date	Price
2024-01-01	85
2024-01-02	90
2024-01-03	88
...	...
2024-01-31	92
2024-02-01	95
2024-02-02	96
...	...
2024-02-28	100

output
Date	Price
2024-01-31	89
2024-02-29	96

In [ ]:
for period in ["D", "W", "M", "A"]:
    df.resample(period).mean().plot()

In [ ]:
brent_new.resample('10D').mean()

In [ ]:
brent_new.resample('8H').interpolate(method = 'linear')

In [ ]:
brent_new.asfreq('10D', method = 'ffill')

In [ ]:
brent_new.asfreq('10D', fill_value = 12)

In [ ]:
brent_new.rolling(2).mean()

In [ ]:
df1.assign(previous_day_sales = df1['sales'].shift(),
           Next_day = df1['sales'].shift(-1), 
           ratio = df1['sales']/df1['sales'].shift()
           )

In [1]:
ercent Tested	SAT Section	Score	Unnamed: 7
0	01-01-2023	A. Philip Randolph Campus High School	Manhattan	1354	74.00%	Math	459	NaN
1	02-01-2023	A. Philip Randolph Campus High School	Manhattan	1354	74.00%	Reading	453	NaN
2	03-01-2023	A. Philip Randolph Campus High School	Manhattan	1354	74.00%	Writing	447	NaN
3	04-01-2023	Abraham Lincoln High School	Brooklyn	2341	            54.90%

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (3118043040.py, line 2)

In [ ]:
sat['Percent Tested'] = sat['Percent Tested'].replace(regex='%', value='').astype('float')

In [ ]:
df.pivot_table(index = '', columns = '', values = '', aggfunc = 'std', margins = True)

In [ ]:
df.pivot_table(index = '', columns = '', values = '', aggfunc = ['mean', 'std']).rename(axis = 1, level = 0, mapper = {'max': 'Maximum_value', 'min': 'Minimum_value'})

In [ ]:
sat.pivot_table('Score', 'Borough' , 'SAT Section', aggfunc=['max', 'min']).rename(axis = 1, level=0,mapper={'max': 'Maximum_Value', 'min': 'Minimum_Value'})

In [ ]:
pivoted = sat.pivot(index = 'School Name', columns = 'SAT Section', values = 'Score')
sat.pivot_table(values = 'Score', index = 'Borough', columns = 'SAT Section', aggfunc = 'std')
sat.pivot_table(values = 'Score', index = 'Borough', columns = 'SAT Section', aggfunc = 'mean')
sat.pivot_table('Score', 'Borough', 'SAT Section', aggfunc= 'mean', margins=True)
sat.pivot_table('Score', ['School Name', 'Borough'] , 'SAT Section')
sat.pivot_table('Score', 'Borough' , 'SAT Section', aggfunc=['max', 'min']).rename(axis = 1, level=0,mapper={'max': 'Maximum_Value', 'min': 'Minimum_Value'})
sat.pivot_table(index='Borough', values='Student Enrollment', aggfunc=['sum', 'mean'])

![image (11).png](<attachment:image (11).png>)

In [ ]:
pd.cross(index = df[''], columns = df[''], values = df[''], aggfunc = 'mean', margins = True, normalize = True)

In [ ]:
pd.crosstab(index = sat['Borough'], columns= sat['SAT Section'], values=sat['Score'], aggfunc='mean', margins=True, normalize=True)
sat.pivot_table(index = 'Borough', columns='SAT Section', values = 'Student Enrollment', aggfunc= 'sum', margins=True)

In [ ]:
pivoted.reset_index().melt(id_vars = 'School name', value_name = 'Score')

In [ ]:
# Unpivot 
pivoted.reset_index().melt(id_vars = 'School Name', value_name='Score')

In [ ]:
df_melted = df.melt(id_vars='Teams', value_vars=['Matches_Played', 'Wins'], 
                    var_name='Statistic', value_name='Value')

![image (12).png](<attachment:image (12).png>)

![image (11).png](<attachment:image (11).png>)

In [3]:
![image (11).png](<attachment:image (11).png>)

The system cannot find the file specified.

In [2]:
c:\Users\Karan Narula\Downloads\image (12).png

SyntaxError: unexpected character after line continuation character (2153417772.py, line 1)

In [ ]:
# how we can apply dense_rank as we apply in SQL

In [ ]:
def rank_movie(row):
    year = row.loc["Year"]
    actor = row.loc["Actor"]
    budget = row.loc["Budget"]

    if year >= 1980 and year < 1990:
        return "Great 80's flick!"

    if actor == "Pierce Brosnan":
        return "The best Bond ever!"

    if budget > 100:
        return "Expensive movie, fun"

    return "No comment"

bond.apply(rank_movie, axis="columns")

In [ ]:
games.query('Genre == "Adventure"')

In [ ]:
Transaction.query('store_nbr == 27')

In [ ]:
# if we want to see all column names
pd.set_option('display.max_columns', 100) 
# want to see all rows
pd.set_option('display.max_rows', 400)

In [ ]:
df['Plcass'].value_count(ascending = False).to_frame()

In [ ]:
df['pclass'].value_counts(ascending = False).to_frame()

output :: convert into dataframe

	   count
pclass	
3	491
1	216
2	184

In [ ]:
df['pclass'].value_counts(ascending = False)

output 

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
pd.to_numeric(df[Quantity], errror = 'coerce')

In [ ]:
Sales_data['Quantity Ordered'] = pd.to_numeric(Sales_data['Quantity Ordered'], errors='coerce')

In [ ]:
duplicate_products = df_duplicated.groupby(['Order ID'])['Product'].apply(lambda x : ','.join(x)).reset_index().rename(columns = {'Product': 'Grouped_Products'})

In [ ]:
df.groupby('Orderid')['Product'].apply(lambda x : ','.join(x)).reset_index().rename(columns = {'Product': 'Grouped_Products'})

In [ ]:
df.groupby('order_id')['Product'].apply(lambda x : ','.join(x)).reset_index().rename(columns = {'Product': 'Grouped_Product'})

Name	Age	M/F	City	State	Country	Official Time	Overall	Gender	Years Ran	First_Name	Last_Name	Phela_nam	Bad_vala_nam
4	Chebet, Wilson	31	M	Marakwet	NaN	KEN	2:12:35	5	5	2015	Chebet	Wilson	Chebet	Wilson
12	Keflezighi, Meb	41	M	San Diego	CA	USA	2:17:00	13	13	2015	Keflezighi	Meb	Keflezighi	Meb
13	Nyasango, Cutbert	34	M	Harara	NaN	ZIM	2:17:40	14	14	2016	Nyasango	Cutbert	Nyasango	Cutbert
14	Korir, Wesley	34	M	Kitale	NaN	KEN	2:18:14	15	15	2015:2016	Korir	Wesley	Korir	Wesley
29	Maravilla, Jorge	39	M	Mill Valley	CA	USA	2:24:27	30	27	2016	Maravilla	Jorge	Maravilla	Jorge
...	...	...	...	...	...	...	...	...	...	...	...	...	...	...
986	Bretz, Virgil	44	M	Mt. Kisco	NY	USA	2:56:02	987	931	2015:2016

In [ ]:
dummies = Boston_Marathon['Years Ran'].str.get_dummies(sep = ':')
dummies

In [ ]:
	2015	2016
0	0	0
1	0	0
2	0	0
3	0	0
4	1	0
...	...	...
995	1	1
996	1	0
997	0	0
998	0	0
999	0	0

In [ ]:
Boston_Marathon.insert(Boston_Marathon.columns.get_loc('Years Ran'), 'Ran 2015', dummies['2015'])
Boston_Marathon.insert(Boston_Marathon.columns.get_loc('Years Ran'), 'Ran 2016', dummies['2016'])

Name	Age	M/F	City	State	Country	Official Time	Overall	Gender	Ran 2015	Ran 2016	Years Ran	First_Name	Last_Name	Phela_nam	Bad_vala_nam
0	Kirui, Geoffrey	24	M	Keringet	NaN	KEN	2:09:37	1	1	0	0	NaN	Kirui	Geoffrey	Kirui	Geoffrey
1	Rupp, Galen	30	M	Portland	OR	USA	2:09:58	2	2	0	0	NaN	Rupp	Galen	Rupp	Galen
2	Osako, Suguru	25	M	Machida-City	NaN	JPN	2:10:28	3	3	0	0	NaN	Osako	Suguru	Osako	Suguru
3	Biwott, Shadrack	32	M	Mammoth Lakes	CA	USA	2:12:08	4	4	0	0	NaN	Biwott	Shadrack	Biwott	Shadrack
4	Chebet, Wilson	31	M	Marakwet	NaN	KEN	2:12:35	5	5	1	0	2015	Chebet	Wilson	Chebet	Wilson
...	...	...	...	...	...	...	...	...	...	...	...	...	...	...	...

In [ ]:
df.groupby('col1').agg(colname = ('col2', 'sum'), gupchup = ('col2', 'mean'))

In [ ]:
# Create a line plot showing the total number of sales by week of the year number
sales["date"].dt.isocalendar().week.value_counts().sort_index().plot()

week
1     197
2     241
3     235
4     213
5     246
6     252
7     292
8     325
9     385
10    347
11    385
12    427
13    546
14    440
15    493
16    459
17    559
18    613
19    848
20    542
21    485
22    377
23    456
24    467
...
52    400

In [ ]:
# Export data into Excel 
df_summary_table  = df.groupby(['Sector', 'Industry']).agg(Sales = ('Revenue', 'sum'), Profit = ('Profits', 'sum'))
df_summary_table = df_summary_table.reset_index()

df_summary_table.to_excel(r'C:\Users\Karan Narula\Downloads\\summary_table.xlsx', sheet_name='Summary', index=False)